INSERT INTO `location` (`id`, `location_number`, `location_name`, `comments`, `is_active`)
VALUES
	(1, 1, 'mailbox', NULL, 1),
	(2, 2, 'driveway', NULL, 0),
	(3, 3, 'garage', NULL, 1),
	(4, 4, 'sidewalk', NULL, 1),
	(5, 5, 'well', NULL, 0),
	(6, 6, 'porch', NULL, 1),
	(7, 7, 'chairs', NULL, 1),
	(8, 8, 'camera', NULL, 1),
	(9, 9, 'storm door', NULL, 1),
	(10, 10, 'front door', NULL, 1),
	(11, 11, 'family room door', NULL, 1),
	(12, 12, 'buddha fountain', NULL, 1),
	(13, 13, 'love seat', NULL, 1),
	(14, 14, 'dresser', NULL, 1),
	(15, 15, 'mirror', NULL, 1),
	(16, 16, 'sticks', NULL, 1),
	(17, 17, 'photos', NULL, 1),
	(18, 18, 'imac', NULL, 1),
	(19, 19, 'desk', NULL, 1),
	(20, 20, 'armwar', NULL, 1),
	(21, 21, 'diningroom entrance', NULL, 1),
	(22, 22, 'silverware case', NULL, 1),
	(23, 23, 'corner chair', NULL, 1),
	(24, 24, 'windows', NULL, 1),
	(25, 25, 'tree', NULL, 1),
	(26, 26, 'painting', NULL, 1),
	(27, 27, 'kitchen door', NULL, 1),
	(28, 28, 'thermostat', NULL, 1),
	(29, 29, 'chandelier', NULL, 1),
	(30, 30, 'diningroom table', NULL, 1),
	(31, 31, 'knives', NULL, 1),
	(32, 32, 'microwave', NULL, 1),
	(33, 33, 'stove', NULL, 1),
	(34, 34, 'oils', NULL, 1),
	(35, 35, 'fruit basket', NULL, 1),
	(36, 36, 'paper towels', NULL, 1),
	(37, 37, 'kitchen window', NULL, 1),
	(38, 38, 'sink', NULL, 1),
	(39, 39, 'back window', NULL, 1),
	(40, 40, 'kitchen table light', NULL, 1),
	(41, 41, 'kitchen table', NULL, 1),
	(42, 42, 'kitchen table chairs', NULL, 1),
	(43, 43, 'entry way to front', NULL, 1),
	(44, 44, 'chair', NULL, 1),
	(45, 45, 'cabinets', NULL, 1),
	(46, 46, 'intercom', NULL, 1),
	(47, 47, 'phone jack', NULL, 1),
	(48, 48, 'basket', NULL, 1),
	(49, 49, 'countertop', NULL, 1),
	(50, 50, 'cookie jar', NULL, 1),
	(51, 51, 'fridge', NULL, 1),
	(52, 52, 'dining room door', NULL, 1);

INSERT INTO `cardinfo` (`id`, `card_number`, `card_name`, `person_name`, `action_name`, `object_name`, `comments`)
VALUES
	(1, 1, 'ace_of_hearts', 'peyton_manning', 'throwing', 'football', NULL),
	(2, 2, '2_of_hearts', 'anna kornikova', 'bending over', 'white tennis dress', NULL),
	(3, 3, '3_of_hearts', 'tom hanks', 'forrest gump running', 'leg braces', NULL),
	(4, 4, '4_of_hearts', 'scarlett johansen', 'throwing up', 'booze bottle', NULL),
	(5, 5, '5_of_hearts', 'julian assange', 'vanishing', 'puff of smoke', NULL),
	(6, 6, '6_of_hearts', 'taylor swift', 'attacked', 'kanye', NULL),
	(7, 7, '7_of_hearts', 'johnny depp', 'looking out', 'window', NULL),
	(8, 8, '8_of_hearts', 'pam anderson', 'running', 'beach', NULL),
	(9, 9, '9_of_hearts', 'steve jobs', 'presenting', 'stage', NULL),
	(10, 10, '10_of_hearts', 'ivanka trump', 'speaking', 'convention', NULL),
	(11, 11, 'jack_of_hearts', 'jesus', 'walking', 'lake', NULL),
	(12, 12, 'queen_of_hearts', 'michelle obama', 'jumping jacks', 'white house', NULL),
	(13, 13, 'king_of_hearts', 'barak obama', 'swatting', 'fly', NULL),
	(14, 14, 'ace_of_diamonds', 'michael jordan', 'dunking', 'basketball', NULL),
	(15, 15, '2_of_diamonds', 'maria sharopova', 'swinging', 'tennis racket', NULL),
	(16, 16, '3_of_diamonds', 'george clooney', 'smoking', 'cigar', NULL),
	(17, 17, '4_of_diamonds', 'julia roberts', 'pushing', 'boobs', NULL),
	(18, 18, '5_of_diamonds', 'trump', 'tweeting', 'phone', NULL),
	(19, 19, '6_of_diamonds', 'madonna', 'dancing', 'stage', NULL),
	(20, 20, '7_of_diamonds', 'kevin costner', 'riding', 'horse', NULL),
	(21, 21, '8_of_diamonds', 'marilyn monroe', 'dress blowing', 'subway vent', NULL),
	(22, 22, '9_of_diamonds', 'bill gates', 'yelling', 'pc', NULL),
	(23, 23, '10_of_diamonds', 'oprah', 'interviewing', 'couch', NULL),
	(24, 24, 'jack_of_diamonds', 'zeus', 'turning into', 'swan', NULL),
	(25, 25, 'queen_of_diamonds', 'princess kate', 'touching', 'dress', NULL),
	(26, 26, 'king_of_diamonds', 'prince william', 'air lifting', 'helocopter', NULL),
	(27, 27, 'ace_of_spades', 'rodman', 'diving', 'cameraman', NULL),
	(28, 28, '2_of_spades', 'annika sorenstam', 'hitting', 'golf ball', NULL),
	(29, 29, '3_of_spades', 'ben stiller', 'testing', 'lie detector', NULL),
	(30, 30, '4_of_spades', 'reece witherspoon', 'playing', 'guitar', NULL),
	(31, 31, '5_of_spades', 'osama', 'blowing up', 'suicide vest', NULL),
	(32, 32, '6_of_spades', 'lady gaga', 'runway', 'meat dress', NULL),
	(33, 33, '7_of_spades', 'anthony weiner', 'selfie', 'mirror', NULL),
	(34, 34, '8_of_spades', 'naomi campbell', 'hitting maid', 'purse', NULL),
	(35, 35, '9_of_spades', 'mr bean', 'slapping', 'queen', NULL),
	(36, 36, '10_of_spades', 'sarah palin', 'shooting', 'moose', NULL),
	(37, 37, 'jack_of_spades', 'dali lama', 'praying', 'buddha', NULL),
	(38, 38, 'queen_of_spades', 'victoria beckham', 'applying', 'lipstick', NULL),
	(39, 39, 'king_of_spades', 'david beckham', 'kicking', 'soccer ball', NULL),
	(40, 40, 'ace_of_clubs', 'mohammad ali', 'punching', 'butterfly', NULL),
	(41, 41, '2_of_clubs', 'serena williams', 'lifting', 'trophy', NULL),
	(42, 42, '3_of_clubs', 'brad pitt', 'punched', 'face', NULL),
	(43, 43, '4_of_clubs', 'angelena jolie', 'karate chop', 'person', NULL),
	(44, 44, '5_of_clubs', 'hitler', 'goosestepping', 'bunker', NULL),
	(45, 45, '6_of_clubs', 'rhianna', 'holding umbrella', 'rain storm', NULL),
	(46, 46, '7_of_clubs', 'arnold', 'shooting', 'gun', NULL),
	(47, 47, '8_of_clubs', 'medusa', 'staring', 'stone', NULL),
	(48, 48, '9_of_clubs', 'bill clinton', 'bombing', 'baby food factory', NULL),
	(49, 49, '10_of_clubs', 'hillary clinton', 'punching', 'poster', NULL),
	(50, 50, 'jack_of_clubs', 'pope', 'baptizing man', 'water', NULL),
	(51, 51, 'queen_of_clubs', 'beyonce', 'power dancing', 'beach', NULL),
	(52, 52, 'king_of_clubs', 'jz', 'rapping', 'microphone', NULL);

-- INSERT INTO `scores` ('timestamp', `master_list_id`, `answer_list_id`, `comments`)
-- VALUES
-- (CURRENT_DATE, 1, 1, 99.96, '1 these are my comments'),
-- 	(CURRENT_DATE,2, 2, 91.00, '2 these are my comments '),
-- 	(CURRENT_DATE, 3, 3, 90.00, '3 these are my comments'),
-- 	(CURRENT_DATE, 4, 5, 99.96, '4 these are my comments');

INSERT INTO `scores` (`timestamp`, `MASTER_LISTID`, `ANSWER_LISTID`, `FINAL_SCORE`, `comments`)
VALUES
	('2017-02-16 00:00:00', 1, 1, 80, 'row 1 comments here for doug'),
('2017-02-16 00:00:00', 2, 2, 80, 'row 1 comments here for doug'),
('2017-02-16 00:00:00', 3, 4, 80, 'row 1 comments here for doug'),
('2017-02-16 00:00:00', 4, 1, 80, 'row 1 comments here for doug');